import React, { useEffect, useRef } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Web3Modal from "web3modal";
import WalletConnectProvider from "@walletconnect/web3-provider";
import Grid from '@mui/material/Grid';
import { theme } from '../styles/Theme';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { useRouter } from 'next/router'
import { useWeb3 } from '../hooks/Web3Contaxt';
import Logo from '../icons/image.svg';
import ChainLogo from '../icons/chainS.png';
import PackLogo from '../icons/packshi.png';
import FuruLogo from '../icons/furuC.png';
import Typewriter from 'typewriter-effect';
import CanvasBackground from '../components/CanvasBackground'
import { height } from '@mui/system';

const Home=({timeout=50})=>{
const {connectWallet,connected}=useWeb3();
const router = useRouter();

useEffect(() => {
  
  if(connected==true){
    router.push("/dashboard")
  }
}, [!connected]);


  return (
    <div
      className={styles.container}
      style={{
        backgroundColor:"transparent",
      }}
    >
      <Head>
        <title>Fountain Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CanvasBackground />
        <Image src={Logo} alt="SVG logo image" width={460} height={250} />
        <Typography className={styles.title} pb={6}>
          <Typewriter
            options={{
              strings: ["Hey you...","Welcome to Fountain Finance", "A Goli product","Connect now...."],
              autoStart: true,
              loop: true,
            }}
          />
        </Typography>

        <Grid
          container
          spacing={2}
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
          
        >
          <Grid item>
            <Button
              variant="contained"
              color="primary"
              onClick={() => connectWallet()}
            >
              CONNECT
            </Button>
          </Grid>
          <Grid container  spacing={1} style={{ 
          backgroundColor:theme.palette.background.paper,
          position: "fixed",
          right:0,
          left: 0,
          bottom: 0,
          width: "100%",
          color: "white",
          height:"15vh",
          display:"flex",
          flexDirection:"row",
          justifyContent:"center",
          alignItems:"center",
          }}>
            <Grid item>
         <Typography fontSize={20} pr={1}>System designed by:</Typography>
         </Grid>
          <Grid item xs={2}>
         <Image src={FuruLogo} alt="SVG logo image" width={200} height={30} />
         </Grid>
         <Grid item >
         <Typography fontSize={20} pr={1} >Audited by:</Typography>
         </Grid>
          <Grid item xs={2}>
         <Image src={ChainLogo} alt="SVG logo image" width={200} height={50} />
         </Grid>
         <Grid item xs={2}>
         <Image src={PackLogo} alt="SVG logo image" width={200} height={50} />
         </Grid>
         <Grid item xs={2}>
         <Typography fontSize={30} fontWeight={'bold'}>HashCloak</Typography>
         </Grid>
        </Grid>
        </Grid>

      </main>
    </div>
  );
}
export default Home