import React, { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Web3 from "web3";
import Web3Modal from "web3modal";
import Fortmatic from "fortmatic";
import WalletConnectProvider from "@walletconnect/web3-provider";
// import Torus from "@toruslabs/torus-embed";
import Portis from "@portis/web3";

export default function Home() {

  let web3Modal;
// Chosen wallet provider given by the dialog window
let provider;
// Address of the selected account
let selectedAccount;
  // Example for Polygon/Matic:
const customNetworkOptions = {
  rpcUrl: 'https://rpc-mainnet.maticvigil.com',
  chainId: 137
}

  const providerOptions = {
  
    walletconnect: {
      package: WalletConnectProvider, // required
      options: {
        infuraId:process.env.NEXT_PUBLIC_INFURA_ID // required
      }
    },
    // fortmatic: {
    //   package: Fortmatic, // required
    //   options: {
    //     key: "FORTMATIC_KEY", // required,
    //     network: customNetworkOptions // if we don't pass it, it will default to localhost:8454
    //   }
    // },
    // // torus: {
    // //   package: Torus, // required
    // //   options: {
    // //     networkParams: {
    // //       host: "https://localhost:8545", // optional
    // //       chainId: 1337, // optional
    // //       networkId: 1337 // optional
    // //     },
    // //     config: {
    // //       buildEnv: "development" // optional
    // //     }
    // //   }
    // // },
    // portis: {
    //   package: Portis, // required
    //   options: {
    //     id: "PORTIS_ID" // required
    //   }
    // }
  };

 useEffect(() => {
  const sub =async()=>{
    web3Modal = new Web3Modal({
      network: "mainnet", // optional
      cacheProvider: true, // optional
      providerOptions, // required
      theme: "dark"
    });
    
   }
sub();

 }, [])

 

  const ConnectWallet=async()=>{
      provider = await web3Modal.connect();  
      // Subscribe to accounts change
    provider.on("accountsChanged", (accounts) => {
      //fetchAccountData();
      console.log("accounts",accounts)
    });
  
    // Subscribe to chainId change
    provider.on("chainChanged", (chainId) => {
      //fetchAccountData();

      console.log("chain ID",chainId)
    });
    
    provider.on("wallet_requestPermissions",(message)=>{
      console.log("chain ID",message)
    })
  }



  const onDisconnect=async()=>{

    console.log("Killing the wallet connection", provider);
  
    // TODO: Which providers have close method?
    if(provider?.close) {
      await provider.close();
      await web3Modal.clearCachedProvider();
      provider = null;
    }
  
    selectedAccount = '';
  
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Fountain Finance
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
          <button onClick={()=>ConnectWallet()}>CONNECT</button>
          <button onClick={()=>onDisconnect()}>DISCONNECT</button>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
