import React, { useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Web3Modal from "web3modal";
import WalletConnectProvider from "@walletconnect/web3-provider";
import Grid from '@mui/material/Grid';
import { theme } from '../styles/Theme';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { useRouter } from 'next/router'
import { useWeb3 } from '../hooks/Web3Contaxt';




const Home=()=>{
const {connectWallet,connected}=useWeb3();
const router = useRouter();
  
useEffect(() => {
  
  if(connected==true){
    router.push("/dashboard")
  }
}, [!connected]);



  return (
    <div className={styles.container} style={{background:theme.palette.background.default}}>
      <Head>
        <title>Fountain Farm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Typography  className={styles.title}>
          Welcome to the Fountain Farm
        </Typography>

        <Typography color="primary" className={styles.description}>
          Get started yield farming
         
          
        </Typography>

        <Grid container spacing={2} style={{display:"flex",justifyContent:"center",alignItems:"center"}}>
          <Grid item >
          <Button variant="contained" color="primary" onClick={()=>connectWallet()}>CONNECT</Button>
          </Grid>
         
        </Grid>
      </main>
    </div>
  )
}
export default Home